#!/bin/sh
### BEGIN INIT INFO
# Provides:          {{name}}
# Required-Start:    $local_fs $network $remote_fs $syslog
# Required-Stop:     $local_fs $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop {{name}}
# Description:       {{description}}
### END INIT INFO

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="{{summary}}"
NAME={{name}}
DAEMON={{exec}}
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

is_running()
{
    [ -f $PIDFILE ] || return 1
    ps -p $(cat $PIDFILE) >/dev/null 2>&1
}

#
# Function that starts the daemon/service
#
do_start()
{
    # Return
    #   0 if daemon has been started
    #   1 if daemon was already running
    #   2 if daemon could not be started
    
    is_running && return 1
    start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile \
        --startas $DAEMON --name $NAME --background -- $DAEMON_ARGS >/dev/null
    cat $PIDFILE >/dev/null 2>&1
    is_running || return 2
    return 0
}

#
# Function that stops the daemon/service
#
do_stop()
{
    # Return
    #   0 if daemon has been stopped
    #   1 if daemon was already stopped
    #   2 if daemon could not be stopped
    #   other if a failure occurred
    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
    RETVAL="$?"
    [ "$RETVAL" = 2 ] && return 2
    # Wait for children to finish too if this is a daemon that forks
    # and if the daemon is only ever run from this initscript.
    # If the above conditions are not satisfied then add some other code
    # that waits for the process to drop all resources that could be
    # needed by services started subsequently.  A last resort is to
    # sleep for some time.
    start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
    [ "$?" = 2 ] && return 2
    # Many daemons don't delete their pidfiles when they exit.
    rm -f $PIDFILE
    return $RETVAL
}

case $1 in
    start)
        [ $VERBOSE != no ] && log_daemon_msg "Starting $DESC" "$NAME"
        do_start
        RETVAL=$?
        [ $VERBOSE = no ] && return $RETVAL
        case $RETVAL in
            0|1) [ $VERBOSE != no ] && log_end_msg 0 ;;
            2) [ $VERBOSE != no ] && log_end_msg 1 ;;
        esac
        ;;
    stop)
        [ $VERBOSE != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
        do_stop
        RETVAL=$?
        [ $VERBOSE = no ] && return $RETVAL
        case $RETVAL in
            0|1) [ $VERBOSE != no ] && log_end_msg 0 ;;
            2) [ $VERBOSE != no ] && log_end_msg 1 ;;
        esac
        ;;
    status)
        status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
        ;;
    restart|force-reload)
        log_daemon_msg "Restarting $DESC" "$NAME"
        do_stop
        RETVAL=$?
        [ $VERBOSE = no ] && return $RETVAL
        case $RETVAL in
            0|1)
                do_start
                RETVAL=$?
                [ $VERBOSE = no ] && return $RETVAL
                case $RETVAL in
                    0) log_end_msg 0 ;;
                    1) log_end_msg 1 ;; # Old process is still running
                    *) log_end_msg 1 ;; # Failed to start
                esac
                ;;
            *)
                # Failed to stop
                log_end_msg 1
                ;;
        esac
        ;;
    *)
        #echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
        echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
        exit 3
        ;;
esac
